import { storeOnCreate as storeOnCreateFunction } from './stores/storeOnCreate';
import { storeOnUpdate as storeOnUpdateFunction } from './stores/storeOnUpdate';
import { itemOnCreate as itemOnCreateFunction } from './items/itemOnCreate';
import { itemOnUpdate as itemOnUpdateFunction } from './items/itemOnUpdate';
import { userOnCreate as userOnCreateFunction } from './users/userOnCreate';
import { userOnUpdate as userOnUpdateFunction } from './users/userOnUpdate';
import { orderOnCreate as orderOnCreateFunction } from './orders/orderOnCreate';
import { orderOnUpdate as orderOnUpdateFunction } from './orders/orderOnUpdate';
import { httpsOnCallVerifyKyc as httpsOnCallVerifyKycFunction } from './https/onCall/httpsOnCallVerifyKyc';
import { httpsOnCallChallengeToVerifyStoreEmail as httpsOnCallChallengeToVerifyStoreEmailFunction } from './https/onCall/httpsOnCallChallengeToVerifyStoreEmail';
import { httpsOnCallChallengeToVerifyStorePhoneNumber as httpsOnCallChallengeToVerifyStorePhoneNumberFunction } from './https/onCall/httpsOnCallChallengeToVerifyStorePhoneNumber';
import { httpsOnCallChallengeToVerifyStoreAddress as httpsOnCallChallengeToVerifyStoreAddressFunction } from './https/onCall/httpsOnCallChallengeToVerifyStoreAddress';
import { priceZaifXymJpyPubSub as priceZaifXymJpyPubSubFunction } from './exchanges/zaif';

export const storeOnCreate = storeOnCreateFunction;
export const storeOnUpdate = storeOnUpdateFunction;
export const itemOnCreate = itemOnCreateFunction;
export const itemOnUpdate = itemOnUpdateFunction;
export const userOnCreate = userOnCreateFunction;
export const userOnUpdate = userOnUpdateFunction;
export const orderOnCreate = orderOnCreateFunction;
export const orderOnUpdate = orderOnUpdateFunction;
export const httpsOnCallVerifyKyc = httpsOnCallVerifyKycFunction;
export const httpsOnCallChallengeToVerifyStoreEmail = httpsOnCallChallengeToVerifyStoreEmailFunction;
export const httpsOnCallChallengeToVerifyStorePhoneNumber = httpsOnCallChallengeToVerifyStorePhoneNumberFunction;
export const httpsOnCallChallengeToVerifyStoreAddress = httpsOnCallChallengeToVerifyStoreAddressFunction;
export const priceZaifXymJpyPubSub = priceZaifXymJpyPubSubFunction;
