name: CD Mainnet Firebase
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['22']
    name: Node ${{ matrix.node }} CD Mainnet Firebase
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Setup node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run build:mainnet
      - run: npx --package=firebase-tools firebase deploy --project=mainnet --token=${{ secrets.FIREBASE_TOKEN }} --force
