name: CD Testnet Firebase
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['16']
    name: Node ${{ matrix.node }} CD Testnet Firebase
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run build:testnet
      - run: npx --package=firebase-tools firebase deploy --project=testnet --token=${{ secrets.FIREBASE_TOKEN }} --force
